export default {
  mn: new Set(['wi', 'ia']),
  mo: new Set(['ia', 'il', 'ar', 'tn', 'ky']),
  wi: new Set(['mi', 'mn', 'ia', 'il']),
  mi: new Set(['wi', 'in', 'oh']),
  il: new Set(['ia', 'mo', 'ky', 'in', 'wi']),
  ar: new Set(['mo', 'tn', 'ms', 'la']),
  ms: new Set(['la', 'ar', 'tn', 'al']),
  al: new Set(['ms', 'tn', 'fl', 'ga']),
  fl: new Set(['al', 'ga']),
  ga: new Set(['fl', 'al', 'sc', 'tn', 'nc']),
  sc: new Set(['ga', 'nc']),
  nc: new Set(['sc', 'tn', 'va']),
  va: new Set(['nc', 'tn', 'wv', 'ky']),
  wv: new Set(['va', 'ky', 'oh', 'pa']),
  pa: new Set(['wv', 'oh']),
  oh: new Set(['pa', 'wv', 'mi', 'ky']),
  in: new Set(['il', 'oh', 'mi', 'ky']),
  ky: new Set(['tn', 'il', 'in', 'oh', 'wv', 'va']),
  tn: new Set(['ar', 'mo', 'ky', 'nc', 'ga', 'al']),
  la: new Set(['ms', 'ar']),
  ia: new Set(['mn', 'wi', 'il', 'mo']),
}