export default {
  mn: ['wi', 'ia'],
  mo: ['ia', 'il', 'ar', 'tn', 'ky'],
  wi: ['mi', 'mn', 'ia', 'il'],
  mi: ['wi', 'in', 'oh'],
  il: ['ia', 'mo', 'ky', 'in', 'wi'],
  ar: ['mo', 'tn', 'ms', 'la'],
  ms: ['la', 'ar', 'tn', 'al'],
  al: ['ms', 'tn', 'fl', 'ga'],
  fl: ['al', 'ga'],
  ga: ['fl', 'al', 'sc', 'tn', 'nc'],
  sc: ['ga', 'nc'],
  nc: ['sc', 'tn', 'va'],
  va: ['nc', 'tn', 'wv', 'ky'],
  wv: ['va', 'ky', 'oh', 'pa'],
  pa: ['wv', 'oh'],
  oh: ['pa', 'wv', 'mi', 'ky'],
  in: ['il', 'oh', 'mi', 'ky'],
  ky: ['tn', 'il', 'in', 'oh', 'wv', 'va'],
  tn: ['ar', 'mo', 'ky', 'nc', 'ga', 'al', 'ms', 'va'],
  la: ['ms', 'ar'],
  ia: ['mn', 'wi', 'il', 'mo'],
}